#!/bin/bash

apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        libboost-chrono-dev \
        libboost-date-time-dev \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-iostreams-dev \
        libboost-program-options-dev \
        libboost-system-dev \
        libboost-thread-dev \
        libboost-timer-dev \
        make \
    && pip3 install --no-cache-dir -r conf/requirements-bigartm.txt \
    && git clone \
        --depth 1 \
        --branch v0.10.0 \
        https://github.com/bigartm/bigartm.git \
        /opt/bigartm \
    && mkdir /opt/bigartm/build \
    && cd /opt/bigartm/build \
    && cmake -DINSTALL_PYTHON_PACKAGE=ON -DPYTHON=python3 .. \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install
